import Head from "next/head";
import Index from "../src/components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Three.js Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Index />
      </main>
    </div>
  );
}
